### ISSUE TITLE
TerriaCube - June 2020 release for DEA MobX-ing

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terria-cube#48]
This release include all the PRs not critical for DEA UX testing (19-21 May 2020): 

- [x] SOS on MobX https://github.com/terriajs/terriajs/issues/3896 and PR https://github.com/TerriaJS/terriajs/pull/4167

- [ ] Timeseries on MobX - https://github.com/TerriaJS/terriajs/pull/4226

- [ ] Clip and ship (TBC) - https://github.com/TerriaJS/terriajs/issues/4340

- [ ] Switch TerriaCube back to using a catalog file controlled by GA (work with them to upgrade that file to TerriaJS version 8 compatible)

**Comment by soyarsauce** [comment]
https://tc-user-testing.terria.io/ exists for DEA to playtest mobx

Renaming this to June 2020 release for the actual DEA mobx-ing timeline, and converting to epic

**Comment by soyarsauce** [comment]
Related:
https://github.com/TerriaJS/terria-cube/issues/48
https://github.com/TerriaJS/de-africa-map/issues/44

**Comment by soyarsauce** [comment]
Real related: https://github.com/TerriaJS/de-australia-map/issues/47

**Comment by AnaBelgun** [comment]
Superseeded by DE Australia and DE Africa end of June releases (linked above).
